### PR TITLE
Check for duplicate exports

### LINKED ISSUE #507: duplicate export names are not prevented
**How to categorize this issue?**

/area robustness
/kind bug
/priority 1

**What happened**:
It is possible to create multiple installations which export the same dataobject. I just copied an existing installation which does nothing except for importing and exporting values and renamed all exports except for one data export.
The second installation succeeded and both installations were listed as owners in the conflicting `DataObject`. This might have been a special case, since both exported the same value, but it still should be prevented.

**What you expected to happen**:
The second installation should not run at all and it should definitely not become `Succeeded`.

**How to reproduce it (as minimally and precisely as possible)**:
I used the manifests in `test/integration/installations/testdata/test1` for my test.

**Anything else we need to know?**:
The whole Landscaper concept relies on the fact that export names are unique and it is clear which export comes from which installation. If this requirement is broken, the dependency management, and subsequently also the landscaper, will not work at all.

**Environment**:

- Landscaper version: `v0.26.0`

### PR DESCRIPTION
**Pull request by Diaphteiros**
**How to categorize this PR?**

/area robustness
/kind technical-debt
/priority 1

**What this PR does / why we need it**:
This PR adds the much required checks that a newly created/updated installation does not declare any export, which is already declared by another installation. This is essential for the Landscaper concept.

**Which issue(s) this PR fixes**:
Fixes #507 

**Release note**:

```bugfix user
Landscaper now verifies that a created/updated installation does not declare exports which are already exported by another installation in the same context. This is checked in the validation webhook as well as during the reconciliation (in case the webhook is disabled). Installations which break this constraint will be denied by the webhook and set to `Failed` during the reconciliation.
```

### CODE REVIEW

**Comment by Diaphteiros** [comment]
The reason for the failed test is solved with #511

File: pkg/landscaper/controllers/installations/controller.go [hunk 1]
```diff
@@ -480,3 +498,26 @@ func (c *Controller) setInstallationPhaseAndUpdate(ctx context.Context, inst *ls
 
 	return lsError
 }
+
+func (c *Controller) checkForDuplicateExports(ctx context.Context, inst *lsv1alpha1.Installation) error {
```
Comment (achimweigel) [inline pkg/landscaper/controllers/installations/controller.go:502]: With the new reconcile logic this works well for subinstallations but with respect to root installations I see problems with race conditions, e.g. if root inst RI-A is just creating its export data including export data EX and during that its spec is modified such that the new spec does not export EX anymore. This does not stop the export data generation of RI-A. If now another root inst RI-B is created also exporting EX and it checks the exports of RI-A is only sees the new spec without EX but EX is currently created resulting in potential problems. Or do I miss here something? 

Perhaps another strategy is to fail working on an installation if it tries to create some export data and this already exists and was created by another installation. Then we do not need a global check and would have no race conditions.

**Review by achimweigel — CHANGES_REQUESTED** [review]

File: pkg/landscaper/controllers/installations/controller.go (hunk 1 above)
Comment (Diaphteiros) [reply pkg/landscaper/controllers/installations/controller.go:494]: You are right, this could happen, although it is somewhat unlikely.
I will add an additional check to the export creation. While only that check would be enough, I don't like the idea of detecting this problem during export creation, so I will keep the other checks in.

File: pkg/landscaper/controllers/installations/controller.go [hunk 2]
```diff
@@ -141,6 +142,14 @@ func (c *Controller) reconcileNew(ctx context.Context, req reconcile.Request) (r
 
 	}
 
+	if inst.Status.ObservedGeneration != inst.Generation {
+		// spec has changed, make sure the exports don't conflict
+		err := c.checkForDuplicateExports(ctx, inst)
+		if err != nil {
+			return reconcile.Result{}, err
+		}
+	}
```
Comment (achimweigel) [inline pkg/landscaper/controllers/installations/controller.go:151]: Is there a reason why you not have removed the coding here?

File: pkg/landscaper/controllers/installations/controller.go (hunk 1 above)
Comment (achimweigel) [reply pkg/landscaper/controllers/installations/controller.go:493]: ok

File: pkg/landscaper/controllers/installations/reconcile.go [hunk 3]
```diff
@@ -158,6 +158,11 @@ func (c *Controller) handleReconcilePhase(ctx context.Context, inst *lsv1alpha1.
 func (c *Controller) handlePhaseInit(ctx context.Context, inst *lsv1alpha1.Installation) (lserrors.LsError, lserrors.LsError) {
 	currentOperation := "handlePhaseInit"
 
+	err := c.checkForDuplicateExports(ctx, inst)
+	if err != nil {
+		return nil, lserrors.BuildLsError(err, currentOperation, "CheckForDuplicateExports", err.Error(), lsv1alpha1.ErrorConfigurationProblem)
```
Comment (achimweigel) [inline pkg/landscaper/controllers/installations/reconcile.go:163]:
```suggestion
		return lserrors.BuildLsError(err, currentOperation, "CheckForDuplicateExports", err.Error(), lsv1alpha1.ErrorConfigurationProblem), nil
```

Comment (achimweigel) [reply pkg/landscaper/controllers/installations/reconcile.go:163]: I would return this as a fatal error instead because manual intervention is required in that case.

**Review by achimweigel — CHANGES_REQUESTED** [review]

**Review by achimweigel — APPROVED** [review]
/lgtm
